# re-adapted from https://github.com/robotology/icub-hri/blob/master/docker/Dockerfile
FROM tensorflow/tensorflow:latest-py3

RUN apt-get install -y lsb-release
RUN echo `lsb_release -cs`

RUN apt-get update -y
RUN apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common wget

RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add -
RUN apt-add-repository "deb https://apt.kitware.com/ubuntu/ `lsb_release -cs` main"

RUN apt-get update -y

RUN apt-get install -y  git \
        build-essential \
        cmake \
        clang \
        ccache
  
RUN pip3 install matplotlib scikit-image scikit-learn ipython opencv-python opencv-contrib-python pydot

# to avoid getting stuck on configuring tzdata, called by python3-tk
ENV TZ=Europe/Rome
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt install -y python3-tk graphviz

RUN apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev  libwebp-dev libtiff5-dev

RUN pip3 install tqdm

# CLEANUP
RUN rm -rf /var/lib/apt/lists/*e

# Enable ccache, for faster recompilation
ENV PATH=/usr/lib/ccache:$PATH



