# re-adapted from https://github.com/robotology/icub-hri/blob/master/docker/Dockerfile
FROM python

RUN apt-get update
RUN pip install doepy matplotlib numpy pandas tqdm
RUN apt-get install -y python3-tk
RUN apt-get update && apt-get install -y python3-opencv
RUN pip install opencv-python
RUN pip install opencv-contrib-python
RUN pip install tabulate
RUN pip install imageio
RUN pip install scikit-learn
CMD [ "bash" ]


